---
abstract: 'argument type classification'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Module::Build: '0'
  Test::More: '0'
  perl: '5.006001'
  strict: '0'
  warnings: '0'
configure_requires:
  Module::Build: '0'
  perl: '5.006001'
  strict: '0'
  warnings: '0'
dynamic_config: 0
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Params-Classify
provides:
  Params::Classify:
    file: lib/Params/Classify.pm
    version: '0.015'
recommends:
  Devel::CallChecker: '0.003'
  XSLoader: '0'
requires:
  Exporter: '0'
  Scalar::Util: '1.01'
  parent: '0'
  perl: '5.006001'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Params-Classify
  license: http://dev.perl.org/licenses/
version: '0.015'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
